/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as MyQuestionsRouteImport } from './routes/my.questions'
import { Route as MyBookingsRouteImport } from './routes/my.bookings'
import { Route as DashboardRouteImport } from './routes/my.dashboard'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

const MyQuestionsRoute = MyQuestionsRouteImport.update({
  id: '/my/questions',
  path: '/my/questions',
  getParentRoute: () => rootRouteImport,
} as any)

const MyBookingsRoute = MyBookingsRouteImport.update({
  id: '/my/bookings',
  path: '/my/bookings',
  getParentRoute: () => rootRouteImport,
} as any)

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/my/questions': typeof MyQuestionsRoute
  '/my/bookings': typeof MyBookingsRoute
  '/dashboard': typeof DashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/my/questions': typeof MyQuestionsRoute
  '/my/bookings': typeof MyBookingsRoute
  '/dashboard': typeof DashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/my/questions': typeof MyQuestionsRoute
  '/my/bookings': typeof MyBookingsRoute
  '/dashboard': typeof DashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$slug' | '/my/questions' | '/my/bookings' | '/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$slug' | '/my/questions' | '/my/bookings' | '/dashboard'
  id: '__root__' | '/' | '/$slug' | '/my/questions' | '/my/bookings' | '/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  MyQuestionsRoute: typeof MyQuestionsRoute
  MyBookingsRoute: typeof MyBookingsRoute
  DashboardRoute: typeof DashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my/questions': {
      id: '/my/questions'
      path: '/my/questions'
      fullPath: '/my/questions'
      preLoaderRoute: typeof MyQuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my/bookings': {
      id: '/my/bookings'
      path: '/my/bookings'
      fullPath: '/my/bookings'
      preLoaderRoute: typeof MyBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  MyQuestionsRoute: MyQuestionsRoute,
  MyBookingsRoute: MyBookingsRoute,
  DashboardRoute: DashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'

import type { startInstance } from './start.ts'

declare module '@tanstack/react-start' {
  interface Register {
    ssr: true

    router: Awaited<ReturnType<typeof getRouter>>

    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}